version: '3.6'


services:
  medidor-crud:
    build: .
    restart: always
    ports:
     - "5000:5000"
     - "50001:50001"
    depends_on:
      - "db"
      - "redis"
    volumes:
      - "./wait-for-it.sh:/wait-for-it.sh:ro"
    command: ["./wait-for-it.sh", "db:5432", "--", "./medidor-crud"]
    environment: # Example ENV configuration
      APP_NAME: "medidor-crud"
      GIN_MODE: "release"
      GIN_HTTPS: "false"
      GIN_ADDR: "0.0.0.0"
      GIN_PORT: "5000"
      LOG_LEVEL: "INFO"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "disable"
      POSTGRES_TIMEZONE: "Asia/Kolkata"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    links:
      - redis
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
       - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
    - 6379:6379
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis
    ports:
      - 8081:8081
    depends_on:
      - redis